version: '3'
services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: sensory-webserver
    restart: on-failure
    ports:
      - '8090:80'
      - '8092:443'
    links:
      - mysql
    volumes:
      - '${DOCUMENT_ROOT-./www}:/var/www/html'
      - '${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini'
      - '${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled'
      - '${LOG_DIR-./logs/apache2}:/var/log/apache2'
  mysql:
    build: ./bin/mysql
    container_name: sensory-mysql
    restart: on-failure
    command:
      - mysqld
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    ports:
      - '3306:3306'
    volumes:
      - '${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensory
      MYSQL_USER: sensory
      MYSQL_PASSWORD: toor
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sensory-phpmyadmin
    restart: on-failure
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8091:80'
    volumes:
      - /sessions
